### Loading data from CSV to PostgreSQL database

In [1]:
!pip install psycopg2
!pip install sqlalchemy

Requirement already satisfied: psycopg2 in c:\users\ankit.khetan\appdata\local\miniconda3\lib\site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in c:\users\ankit.khetan\appdata\local\miniconda3\lib\site-packages (2.0.38)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ankit.khetan\appdata\local\miniconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ankit.khetan\appdata\local\miniconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [2]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

### Creating PostgreSQL connection

In [3]:
host = 'localhost'
user = 'postgres'
password = 'ankit123'
database = 'postgres'

engine = create_engine(f'postgresql://{user}:{password}@{host}:5432/{database}')

In [4]:
csv_file = 'data/Crime_Incidents_in_2024.csv'
df = pd.read_csv(csv_file)

In [5]:
df.to_sql('crime_incidents', engine, if_exists='replace', index=False)

294

In [6]:
df

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,399622.2700,134352.62,24093246,2024/06/19 14:52:56+00,DAY,OTHERS,THEFT/OTHER,1100 - 1199 BLOCK OF NEW JERSEY AVENUE SE,399622.270000,134352.620000,...,007203 1,7203.0,Precinct 131,38.877004,-77.004353,CAPITOL RIVERFRONT,2024/06/19 14:50:00+00,2024/06/19 14:52:00+00,679448603,NaN
1,398579.1351,134828.40,24131497,2024/08/27 01:13:37+00,EVENING,OTHERS,THEFT F/AUTO,300 - 399 BLOCK OF G STREET SW,398579.135069,134828.399995,...,010500 2,10500.0,Precinct 128,38.881289,-77.016376,SOUTHWEST,2024/08/26 18:51:00+00,2024/08/26 20:14:00+00,679448604,NaN
2,396836.0500,139850.46,24120734,2024/08/07 07:10:35+00,MIDNIGHT,OTHERS,THEFT/OTHER,16TH STREET NW AND COLUMBIA ROAD NW,396836.050011,139850.459999,...,003901 1,3901.0,Precinct 39,38.926525,-77.036488,NaN,2024/08/04 01:00:00+00,2024/08/04 01:30:00+00,679449098,NaN
3,398010.0800,138818.94,24168124,2024/10/30 03:40:30+00,MIDNIGHT,OTHERS,THEFT/OTHER,2000 - 2099 BLOCK OF 8TH STREET NW,398010.080000,138818.940000,...,003500 3,3500.0,Precinct 37,38.917236,-77.022946,NaN,2024/10/29 04:00:00+00,2024/10/29 20:00:00+00,679449103,NaN
4,397424.6800,141258.25,24172277,2024/11/05 23:15:06+00,EVENING,OTHERS,MOTOR VEHICLE THEFT,3900 - 3999 BLOCK OF 13TH STREET NW,397424.680000,141258.250000,...,002503 1,2503.0,Precinct 47,38.939209,-77.029705,NaN,2024/11/05 22:22:00+00,NaN,679449104,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29289,404105.0000,139186.00,24087036,2024/06/08 18:13:45+00,DAY,OTHERS,THEFT/OTHER,2400 BLOCK OF MARKET STREET NE,404105.000000,139186.000000,...,009000 3,9000.0,Precinct 139,38.920536,-76.952663,NaN,2024/06/08 17:15:00+00,2024/06/08 19:35:00+00,680014142,NaN
29290,404105.0000,139186.00,24174446,2024/11/09 23:01:38+00,EVENING,OTHERS,THEFT/OTHER,2400 BLOCK OF MARKET STREET NE,404105.000000,139186.000000,...,009000 3,9000.0,Precinct 139,38.920536,-76.952663,NaN,2024/11/09 21:30:00+00,2024/11/09 22:00:00+00,680014153,NaN
29291,402061.0000,135138.00,24145368,2024/09/20 14:29:36+00,DAY,OTHERS,MOTOR VEHICLE THEFT,1900 BLOCK OF D STREET SE,402061.000000,135138.000000,...,006804 1,6804.0,Precinct 80,38.884077,-76.976246,NaN,2024/09/19 20:15:00+00,2024/09/20 12:10:00+00,680014169,NaN
29292,404105.0000,139186.00,24088869,2024/06/11 21:37:49+00,EVENING,OTHERS,THEFT/OTHER,2400 BLOCK OF MARKET STREET NE,404105.000000,139186.000000,...,009000 3,9000.0,Precinct 139,38.920536,-76.952663,NaN,2024/06/11 19:29:00+00,2024/06/11 19:45:00+00,680014176,NaN
29293,402061.0000,135138.00,24187942,2024/12/04 23:19:04+00,EVENING,KNIFE,ASSAULT W/DANGEROUS WEAPON,1900 BLOCK OF D STREET SE,402061.000000,135138.000000,...,006804 1,6804.0,Precinct 80,38.884077,-76.976246,NaN,2024/12/04 18:18:00+00,2024/12/04 18:20:00+00,680014189,NaN